### PR TITLE
fix: Add API experiment unit tests. Closes #18.

### LINKED ISSUE #18: Figure out how to test the experiment

### PR DESCRIPTION
**Pull request by AdamHillier**

### CODE REVIEW

File: experiment/api.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ class API extends ExtensionAPI { // eslint-disable-line no-unused-vars
     for (const prop in manifestOptions) {
       // Necessary to avoid overwriting default values with null if no option is
       // provided in the manifest
-      if (manifestOptions[prop] === null) { manifestOptions[prop] = undefined; }
+      if (manifestOptions[prop] === null) { delete manifestOptions[prop]; }
```
Comment (AdamHillier) [inline experiment/api.js:27]: Tests showed this wasn't working.... 😉

File: experiment/api.js [hunk 2]
```diff
@@ -60,12 +57,11 @@ class API extends ExtensionAPI { // eslint-disable-line no-unused-vars
     const id = this.extension.id;
     const options = this.sectionOptions;
 
-    const updateSection = () => SectionsManager.sections.has(id) &&
-      SectionsManager.updateSection(id, options, true);
-
     // If we dynamically update a section option, propagate the change to
     // Activity Stream
-    const onUpdateOption = () => SectionsManager.onceInitialized(updateSection);
+    const onUpdateOption = () =>
```
Comment (AdamHillier) [inline experiment/api.js:62]: Realised we can do this whether the SM is initialised or not

File: experiment/api.js [hunk 3]
```diff
@@ -101,10 +97,8 @@ class API extends ExtensionAPI { // eslint-disable-line no-unused-vars
       // ActivityStream is responsible for setting the `enabled` property based
       // on whether the user had hidden the extension in the previous session.
       enable() {
-        SectionsManager.onceInitialized(() => {
-          SectionsManager.addSection(id, options);
-          SectionsManager.enableSection(id);
-        });
+        SectionsManager.addSection(id, options);
+        SectionsManager.enableSection(id);
```
Comment (AdamHillier) [inline experiment/api.js:101]: Ditto
